shutdown_costmaps: false

controller_frequency: 5.0
controller_patience: 3.0

planner_frequency: 0.0
planner_patience: 3.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: true
