<?xml version="1.0"?>
<robot name="wheel" xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- Begin - Include -->
  <xacro:include filename="$(find rover_desc_pkg)/urdf/rover_parameters.xacro"/>
  <xacro:include filename="$(find rover_desc_pkg)/urdf/links_joints.xacro"/>
  <xacro:include filename="$(find rover_desc_pkg)/urdf/common_constants.xacro"/>
  <!-- End - Include -->

  <xacro:macro name="wheel" params="fr lr parent translateX translateY"> <!-- fr: front, rear; lr: left, right -->
    <!-- Parameters to compute inertia -->
    <xacro:property name="m" value="${wheel_mass}" scope="local"/>
    <xacro:property name="r" value="${wheel_radius}" scope="local"/>
    <xacro:property name="h" value="${wheel_height}" scope="local"/>

    <!-- Compute wheel position based on its location -->
    <xacro:property name="wheel_x" value="${translateX * world_x_origin_to_wheel_x_origin}" scope="local"/>
    <xacro:property name="wheel_y" value="${translateY * world_y_origin_to_wheel_y_origin}" scope="local"/>
    <xacro:property name="wheel_z" value="${wheel_radius}" scope="local"/>
    <xacro:if value="${lr == 'right'}">
        <xacro:property name="wheel_z" value="${wheel_radius + 0.0032}" scope="local"/>
    </xacro:if>

    <xacro:m_link_mesh_cyl name="${fr}_${lr}_wheel"
                           origin_rpy="0 0 0"
                           origin_xyz="0 0 0"
                           r="${r}"
                           l="${h}"
                           m="${m}"
                           meshfile="package://rover_desc_pkg/meshes/wheel.stl"
                           meshscale="1 1 1"/>

    <gazebo reference="${fr}_${lr}_wheel">
      <material>Gazebo/Black</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

    <xacro:m_joint_cont name="${parent}__${fr}_${lr}_wheel"
                        axis_xyz="0 1 0"
                        origin_rpy="0 0 0"
                        origin_xyz="${steer_x_origin_to_wheel_x_origin}
                                    ${steer_y_origin_to_wheel_y_origin}
                                    ${-steer_z_origin_to_wheel_z_origin}"
                        parent="${parent}" child="${fr}_${lr}_wheel"
                        limit_e="100" limit_v="25"
                        damp="1.0" fric="2.0"/>
  </xacro:macro>

<!-- this can be used for defining a wheel without a motor, not the best place to keep this-->
 <!-- continuous joint without transmission -->
  <xacro:macro name="no_trans" params="name axis_xyz origin_xyz origin_rpy parent child limit_e limit_v">
    <joint name="${name}" type="continuous">
      <axis xyz="${axis_xyz}"/>
      <limit effort="${limit_e}" velocity="${limit_v}"/>
      <origin rpy="${origin_rpy}" xyz="${origin_xyz}"/>
      <parent link="${parent}"/>
      <child link="${child}"/>
      <joint_properties damping="6.0" friction="4.0" />
    </joint>

  </xacro:macro>

   <xacro:macro name="wheels_no_motor" params="fr lr parent translateX translateY"> <!-- fr: front, rear; lr: left, right -->
    <!-- Parameters to compute inertia -->
    <xacro:property name="m" value="${wheel_mass}" scope="local"/>
    <xacro:property name="r" value="${wheel_radius}" scope="local"/>
    <xacro:property name="h" value="${wheel_height}" scope="local"/>

    <!-- Compute wheel position based on its location -->
    <xacro:property name="wheel_x" value="${translateX * world_x_origin_to_wheel_x_origin}" scope="local"/>
    <xacro:property name="wheel_y" value="${translateY * world_y_origin_to_wheel_y_origin}" scope="local"/>
    <xacro:property name="wheel_z" value="${wheel_radius}" scope="local"/>
    <xacro:if value="${lr == 'right'}">
        <xacro:property name="wheel_z" value="${wheel_radius + 0.0032}" scope="local"/>
    </xacro:if>

    <xacro:m_link_mesh_cyl name="${fr}_${lr}_wheel"
                           origin_rpy="0 0 0"
                           origin_xyz="0 0 0"
                           r="${r}"
                           l="${h}"
                           m="${m}"
                           meshfile="package://rover_desc_pkg/meshes/rover_wheel.dae"
                           meshscale="1 1 1"/>

    <gazebo reference="${fr}_${lr}_wheel">
      <material>Gazebo/Black</material>
      <turnGravityOff>false</turnGravityOff>
    </gazebo>

     <xacro:no_trans name="${parent}__${fr}_${lr}_wheel"
                        axis_xyz="0 1 0"
                        origin_rpy="0 0 0"
                        origin_xyz="${steer_x_origin_to_wheel_x_origin}
                                    ${steer_y_origin_to_wheel_y_origin}
                                    ${-steer_z_origin_to_wheel_z_origin}"
                        parent="${parent}" child="${fr}_${lr}_wheel"
                        limit_e="1000" limit_v="25"/>
  </xacro:macro>
  
</robot>

 